---
namespace: passwork
name: passwork_api
version: 1.0.0                          # Collection semantic version
authors:                                # List of authors
  - EFIS
description: Modules for passwork python-connector
tags:                                   # Tags to help find collection.
  - passwork                     
readme: README.md                       # Path to the main README file
repository: https://github.com/es-support-mg22/ansible-collection-passwork
